/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class bbm_webrtc_rtc4j_core_ImageUtils */

#ifndef _Included_bbm_webrtc_rtc4j_core_ImageUtils
#define _Included_bbm_webrtc_rtc4j_core_ImageUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     bbm_webrtc_rtc4j_core_ImageUtils
 * Method:    scaleImage
 * Signature: (Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;Ljava/nio/ByteBuffer;III)I
 */
JNIEXPORT jint JNICALL Java_bbm_webrtc_rtc4j_core_ImageUtils_scaleImage
  (JNIEnv *, jclass, jobject, jobject, jobject, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
